Fixed 'webexmeetings' URL
Installomator/Installomator pull request #192
Opened 2021-06-21 11:52 UTC by adibue

The URL for `webexmeetings` appears to have changed yet another time.
Good thing: The downloaded `pkg` contains the versions for Intel and Apple Silicon at the same time. So no additional URL required :-)

2021-07-06 14:30 UTC, acodega requested changes
Can you post output when you run this label? When I test, curl is not finishing the download, the connection is being closed from the server.

2021-07-07 16:27 UTC, adibue commented
The download appears to be really slow at the moment. However, it worked for me using the web browser after like the 3rd attempt. I'll try it out again tomorrow.

2021-07-09 07:27 UTC, adibue commented
@acodega The download works for me now:

```
2021-07-09 09:24:53 webexmeetings setting variable from argument DEBUG=0
2021-07-09 09:24:53 webexmeetings ################## Start Installomator v. 0.5.0
2021-07-09 09:24:53 webexmeetings ################## webexmeetings
2021-07-09 09:24:53 webexmeetings BLOCKING_PROCESS_ACTION=prompt_user
2021-07-09 09:24:53 webexmeetings NOTIFY=success
2021-07-09 09:24:53 webexmeetings LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2021-07-09 09:24:53 webexmeetings Changing directory to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.iyo2f7ey
2021-07-09 09:24:53 webexmeetings found app at /Applications/Cisco Webex Meetings.app, version 41.6.4.8
2021-07-09 09:24:53 webexmeetings appversion: 41.6.4.8
2021-07-09 09:24:53 webexmeetings Latest version not specified.
2021-07-09 09:24:53 webexmeetings Downloading https://akamaicdn.webex.com/client/Cisco_Webex_Meetings.pkg to Cisco Webex Meetings.pkg
2021-07-09 09:25:02 webexmeetings no more blocking processes, continue with update
2021-07-09 09:25:02 webexmeetings Installing Cisco Webex Meetings
2021-07-09 09:25:02 webexmeetings Verifying: Cisco Webex Meetings.pkg
2021-07-09 09:25:02 webexmeetings Team ID: DE8Y96K9QP (expected: DE8Y96K9QP )
2021-07-09 09:25:02 webexmeetings Installing Cisco Webex Meetings.pkg to /Applications
installer: Package name is Cisco Webex Meetings
installer: Upgrading at base path /
installer: The upgrade was successful.
2021-07-09 09:25:24 webexmeetings Finishing…
2021-07-09 09:25:34 webexmeetings found app at /Applications/Cisco Webex Meetings.app, version 41.7.3.13
2021-07-09 09:25:34 webexmeetings Installed Cisco Webex Meetings, version 41.7.3.13
2021-07-09 09:25:34 webexmeetings notifying
2021-07-09 09:25:35 webexmeetings Deleting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.iyo2f7ey
2021-07-09 09:25:35 webexmeetings App not closed, so no reopen.
2021-07-09 09:25:35 webexmeetings ################## End Installomator, exit code 0
```

2021-07-09 09:17 UTC, adibue commented
...and it's gone again.
I just created a support ticket with Cisco. There seems to be something wrong with their CDN.

2021-07-12 06:52 UTC, adibue commented
I got a reply from Cisco support.
It appears that Webex Meetings is no more and has been replaced by just Webex.
So here's what I'd do:
Create another PR which adds a Label for `webex` and removes the Apple Silicon download in `webexmeetings` (since the Intel download appears to be fine).

2021-07-12 06:53 UTC, closed without merging

2022-04-18 01:55 UTC, jhbush commented
The URL seems to have changed again or is different. https://akamaicdn.webex.com/client/webexapp.dmg (current label URL) contains an Intel only .pkg version of the tools while https://akamaicdn.webex.com/client/Cisco_Webex_Meetings.pkg contains both Intel and Apple Silicon versions of the tool.